# Generated by Django 3.2.9 on 2021-11-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
